CREATE DATABASE IF NOT EXISTS TP8;
USE TP8;

CREATE TABLE IF NOT EXISTS EMPLOYES (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOM NVARCHAR(30) NOT NULL,
    MANAGER_ID INT
);

-- Insertion des données 
-- test qcm
USE TP6;

DESCRIBE formulaires;

SHOW COLUMNS FROM formulaires;
-- test qcm
